# Generated by Django 3.2 on 2021-04-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('univ_id', models.CharField(max_length=20, verbose_name='University ID')),
                ('l_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('f_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
