# Generated by Django 3.2 on 2021-04-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='User ID (Autogenerated)')),
                ('type', models.IntegerField(choices=[(0, 'Admin'), (1, 'Professor'), (2, 'Ta')], verbose_name='User Type')),
                ('univ_id', models.CharField(max_length=20, verbose_name='University ID')),
                ('l_name', models.CharField(max_length=20, verbose_name='Last Name')),
                ('f_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('email', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
    ]
