# Generated by Django 3.2 on 2021-04-14 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0003_auto_20210414_0002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminUser',
        ),
    ]
