# Generated by Django 3.2 on 2021-04-16 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0004_delete_adminuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Id (Autogenerated)')),
                ('course_code', models.CharField(max_length=4, verbose_name='Course Code')),
                ('course_name', models.TextField(max_length=40, verbose_name='Course Name')),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AddField(
            model_name='user',
            name='tmp_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='f_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='l_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Last Name'),
        ),
        migrations.CreateModel(
            name='CourseSection',
            fields=[
                ('course_section_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Course Section ID')),
                ('course_section_code', models.CharField(max_length=3, verbose_name='Course Section Code')),
                ('lecture_days', models.CharField(blank=True, max_length=6, verbose_name='Lecture Day(s)')),
                ('lecture_time', models.TextField(blank=True, max_length=12, verbose_name='Lecture Time')),
                ('course_id', models.ForeignKey(help_text='Course ID', on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.course')),
                ('instructor_id', models.ForeignKey(blank=True, help_text='Instructor ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.user')),
            ],
            options={
                'unique_together': {('course_section_code', 'course_id')},
            },
        ),
        migrations.AddField(
            model_name='course',
            name='admin_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.user'),
        ),
        migrations.CreateModel(
            name='LabSection',
            fields=[
                ('lab_section_id', models.AutoField(primary_key=True, serialize=False, verbose_name='Lab Section ID')),
                ('lab_section_code', models.CharField(max_length=3, verbose_name='Lab Section Code')),
                ('lab_days', models.CharField(blank=True, max_length=6, verbose_name='Lab Day(s)')),
                ('lab_time', models.TextField(blank=True, max_length=12, verbose_name='Lab Time')),
                ('course_section_id', models.ForeignKey(help_text='Course Section ID', on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.coursesection')),
                ('ta_id', models.ForeignKey(blank=True, help_text='TA ID', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.user')),
            ],
            options={
                'unique_together': {('course_section_id', 'lab_section_code')},
            },
        ),
        migrations.CreateModel(
            name='TACourseSectionAssign',
            fields=[
                ('course_section_id', models.ForeignKey(help_text='Course Section ID', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='TAScheduler.coursesection')),
                ('ta_id', models.ForeignKey(help_text='TA ID', on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user')),
            ],
            options={
                'unique_together': {('course_section_id', 'ta_id')},
            },
        ),
    ]
