# Generated by Django 3.2 on 2021-04-20 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0005_auto_20210416_0334'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesection',
            name='ta_ids',
            field=models.ManyToManyField(help_text='Tas Assigned to this Course Section', related_name='section_assign', to='TAScheduler.User'),
        ),
        migrations.AlterUniqueTogether(
            name='labsection',
            unique_together={('lab_section_code', 'course_section_id')},
        ),
        migrations.DeleteModel(
            name='TACourseSectionAssign',
        ),
    ]
