# Generated by Django 3.2 on 2021-04-20 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0006_auto_20210420_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesection',
            name='ta_ids',
            field=models.ManyToManyField(blank=True, help_text='Tas Assigned to this Course Section', related_name='section_assign', to='TAScheduler.User'),
        ),
    ]
