# Generated by Django 3.2 on 2021-04-29 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TAScheduler', '0008_auto_20210429_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent', models.DateTimeField(blank=True, help_text='Sent date', null=True)),
                ('title', models.CharField(blank=True, help_text='Title', max_length=60)),
                ('body', models.TextField(help_text='Body', max_length=500)),
                ('parent', models.ForeignKey(blank=True, help_text='In response to', null=True, on_delete=django.db.models.deletion.SET_NULL, to='TAScheduler.message')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='Skill')),
            ],
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read', models.DateTimeField(blank=True, help_text='Read date', null=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.message')),
                ('recipient', models.ForeignKey(help_text='To', on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='recipients',
            field=models.ManyToManyField(help_text='To', related_name='messages_received', through='TAScheduler.Recipient', to='TAScheduler.User'),
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(help_text='From', on_delete=django.db.models.deletion.CASCADE, to='TAScheduler.user'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, help_text='What skills does this user possess?', to='TAScheduler.Skill'),
        ),
    ]
