name: Django Tests
on:
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.7', '3.9']
        suite: ['TAScheduler.acceptance_tests', 'TAScheduler.UnitTests', 'TAScheduler.viewsupport']

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Django Tests for ${{ matrix.suite }}
      run: |
        python3 manage.py test ${{ matrix.suite }}
