from django.db import models
from enum import Enum


class User(models.Model):
    """
    Represents all three types of user of our application
    """
    class UserType(models.TextChoices):
        ADMIN = "A", ("Administrator")
        PROF = "P", ("Professor")
        TA = "T", ("TA")

    user_id = models.AutoField('User ID (Autogenerated)', primary_key=True)
    type = models.CharField('User Type', max_length=1, choices=UserType.choices, blank=False)

    """The first part of the university email"""
    univ_id = models.CharField('University ID', max_length=20)

    l_name = models.CharField('Last Name', max_length=20)
    f_name = models.CharField('First Name', max_length=20)

    phone = models.CharField(max_length=10, blank=True)

    """
    Output of a Password Hasher
    see: https://docs.djangoproject.com/en/3.2/topics/auth/passwords/
    """
    password = models.CharField(max_length=64)
    tmp_password = models.BooleanField(default=True, blank=False)

    def __str__(self):
        return f'{self.f_name} {self.l_name} ({self.email}) [{self.get_type_display()}]'


